---
apiVersion: v1
kind: Pod
metadata:
  name: api-endpoint
  labels:
    app: api-endpoint
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: server
    image: hashicorp/http-echo
    imagePullPolicy: IfNotPresent
    args:
    - -text="hello world"
    - -listen=:8080
    ports:
    - name: http
      port: 8080
      containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-endpoint
spec:
  selector:
    app: api-endpoint
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
