---
apiVersion: v1
kind: Pod
metadata:
  name: camel-proxy
  labels:
    app: camel-proxy
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: server
    image: quay.io/zregvart/camel-netty-proxy
    imagePullPolicy: Always
    ports:
    - name: plaintext
      port: 8080
      containerPort: 8080
    - name: tls
      port: 8443
      containerPort: 8443
    volumeMounts:
      - name: certs
        mountPath: /certs/
      - name: tls-jks
        mountPath: /tls/
    env:
      - name: LOG_LEVEL
        value: DEBUG
  initContainers:
  - name: tls-certificate
    image: docker.io/jimmidyson/pemtokeystore:latest
    args:
    - -cert-file
    - server=/certs/tls.crt
    - -key-file
    - server=/certs/tls.key
    - -keystore
    - /tls-jks/keystore.jks
    - -keystore-password
    - changeit
    volumeMounts:
      - name: certs
        mountPath: /certs/
      - name: tls-jks
        mountPath: /tls-jks/
  volumes:
    - name: certs
      secret:
        secretName: camel-proxy
    - name: tls-jks
      emptyDir:
        medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: camel-proxy
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: camel-proxy
spec:
  selector:
    app: camel-proxy
  ports:
  - name: plaintext
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: tls
    port: 8443
    protocol: TCP
    targetPort: 8443
