---
apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: client
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: client
    image: docker.io/cilium/demo-client
    imagePullPolicy: IfNotPresent
    command: [ "sleep" ]
    args:
    - "1000h"
