---
apiVersion: v1
kind: Pod
metadata:
  name: api-endpoint
  labels:
    app: api-endpoint
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: server
    image: mendhak/http-https-echo
    imagePullPolicy: IfNotPresent
    ports:
    - name: dns
      port: 80
      containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-endpoint
spec:
  selector:
    app: api-endpoint
  clusterIP: 172.30.136.12
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
